EnigmaticaModpacks/Enigmatica9

- config/theoneprobe-common.toml
> Make theoneprobe not require a probe

- kubejs/server_scripts/base/recipes/blue_skies/shaped.js
- kubejs/server_scripts/base/recipes/blue_skies/shapeless.js
- kubejs/server_scripts/base/tags/blocks/forge/storage_blocks.js
- kubejs/server_scripts/base/tags/items/forge/raw_materials.js
- kubejs/server_scripts/base/tags/items/forge/storage_blocks.js
- kubejs/server_scripts/constants/gem_properties.js
Fixing fallout from fixing blue skies tags.
> More cleanup of blue skies materials

- config/configswapper/expert/serverconfig/immersiveengineering-server.toml
- config/configswapper/normal/serverconfig/immersiveengineering-server.toml
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/immersiveengineering/blastfurnace_fuel.js
- kubejs/server_scripts/packmode.js
Seems to be working perfectly for swapping configs. KubeJS script needed a minor tweak to update the event handler. Recipe swapping now works perfectly on `kubejs-forge-1902.6.0-build.67`
> Config Swapper - Begin setup for 2p1p

- kubejs/server_scripts/base/entity/spawned/equipment.js
In regards to https://github.com/EnigmaticaModpacks/Enigmatica9/pull/32#discussion_r975576892
> clarify mob type and mod id in equipment script

- kubejs/server_scripts/base/loot_tables/entities/twilightforest/death_tome.js
- kubejs/server_scripts/functions.js
Adds Tier 1 Ars glyphs to Death Tomes. Sets up generic functions to assist with future loot table modifications.
> Set up Loot Table functions for easily adding loot tables to mobs

- config/configswapper/expert/config/blue_skies-common.toml
- config/configswapper/expert/config/naturesaura-common.toml
- config/configswapper/expert/config/quark-common.toml
- config/configswapper/expert/config/twilightforest-common.toml
- config/configswapper/normal/config/blue_skies-common.toml
- config/configswapper/normal/config/naturesaura-common.toml
- config/configswapper/normal/config/quark-common.toml
- config/configswapper/normal/config/twilightforest-common.toml
- kubejs/client_scripts/base/jei_descriptions.js
- kubejs/server_scripts/expert/gamerules/default.js
- kubejs/server_scripts/expert/tags/items/twilightforest/portal_activator.js
Attempting to trim down Quark a bit and setting up basic config swapping for expert/normal
> Config Swapper - Setting up Quark

- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/naturesaura/animal_spawner.js
- kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
Probably temp recipes, just getting the handlers working
> Set up basic NA recipe handlers

- kubejs/server_scripts/base/entity/spawned/custom_rituals.js
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
- kubejs/server_scripts/functions.js
rhino-forge-1802.2.0-build.237 fixed issues with mappings, so no need to use MC mappings anymore. Updated scripts to work again.
> Update ritual and entity summon scripts 

- kubejs/server_scripts/expert/recipes/immersiveengineering/blastfurnace_fuel.js
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/naturesaura/animal_spawner.js
- kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
- kubejs/server_scripts/expert/recipes/occultism/ritual.js
no longer needed, seems the bug was fixed in kube.
> Cleanup string validation on scripts

- kubejs/server_scripts/expert/tags/items/twilightforest/portal_activator.js
Forgot to make this expert only.
> Fix Twilight Forest portal

- kubejs/server_scripts/constants/no_despawn.js
- kubejs/server_scripts/expert/entity_events/spawned/no_despawn.js
- kubejs/server_scripts/expert/recipes/lychee/item_inside.js
- kubejs/server_scripts/expert/recipes/lychee/lightning_channeling.js
- kubejs/server_scripts/expert/tags/items/lychee/fire_immune.js
These recipes won't last, but the concepts will. Preserving here as they're tested and working.
> [Expert] Lychee test scripts and examples

- config/ftbquests/quests/chapters/storage.snbt
Correcting information on Functional Storage, updating Sophisticated Storage/Backpacks. Improved layout.
> Update Storage quests

- config/ftbquests/quests/chapters/ars_nouveau.snbt
Overhaul of the Ars Nouveau quests, including many of the new items and mechanics.
> Ars Nouveau Quest Refresh

- kubejs/server_scripts/functions.js
- kubejs/server_scripts/settings.js
latest version changed the way Java() is called, as well as where settings are stored.
> updates for new KubeJS version

- config/ftbquests/quests/chapters/hidden_quests.snbt
- config/ftbquests/quests/chapters/natures_aura.snbt
- config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
- config/ftbquests/quests/chapters/tools.snbt
- config/patchouli-client.toml
- kubejs/config/common.properties
Complete refresh of PNC quests
> PneumaticCraft Quest refresh

- kubejs/server_scripts/constants/armored_mobs.js
- kubejs/server_scripts/constants/equipment_nbt.js
converts armored mobs to use the same equipment nbt  constants as apotheosis.
> Drowned now have a chance to drown their attackers

- config/configswapper/expert/config/apotheosis/adventure.cfg
- config/configswapper/normal/config/apotheosis/adventure.cfg
- kubejs/server_scripts/base/loot_tables/chests/apotheosis/spawner_swarm.js
Make affix loot and gems a touch more rare
add spawners to other dimensions
adjust spawner swarm loot table to no longer drop spawn eggs.
> Apotheosis adjustments

- config/configswapper/expert/serverconfig/create-server.toml
- config/configswapper/normal/serverconfig/create-server.toml
- config/ftbquests/quests/chapters/create.snbt
- kubejs/server_scripts/base/tags/blocks/create/passive_boiler_heaters.js
Increases Storage Capacity for Tanks and Vaults
Re-work of quests, changing the layout, updating text, etc.
Experimental config changes for Expert
> Create Quest update

- kubejs/server_scripts/base/entity/spawned/equipment.js
Context is on #Contributor Chat 😅
PS: There are also java errors with boots.js, but I have no idea how to fix those >.>
> Fix errors in equipment.js

- kubejs/client_scripts/base/tooltips.js
> More visible Wither Immune tooltip

- kubejs/server_scripts/base/recipes/enigmatica/dye_crushing.js
Fix for #153 until #161 can be fully resolved
> temp dye fix

- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_moonstone.json
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/immersiveengineering/fermenter.js
- kubejs/server_scripts/base/recipes/immersiveengineering/refinery.js
- kubejs/server_scripts/base/recipes/immersiveengineering/squeezer.js
- kubejs/server_scripts/base/recipes/mekanism/crushing.js
- kubejs/server_scripts/base/recipes/mekanism/pigment_extracting.js
- kubejs/server_scripts/base/recipes/pneumaticcraft/thermo_plant.js
- kubejs/server_scripts/base/recipes/thermal/brewer.js
- kubejs/server_scripts/base/recipes/thermal/insolator_catalyst.js
- kubejs/server_scripts/base/recipes/thermal/press.js
- kubejs/server_scripts/base/recipes/thermal/pulverizer.js
- kubejs/server_scripts/base/recipes/thermal/pulverizer_catalyst.js
- kubejs/server_scripts/base/recipes/thermal/pyrolyzer.js
- kubejs/server_scripts/base/recipes/thermal/smelter_catalyst.js
- kubejs/server_scripts/base/recipes/thermal/tree_extractor_boost.js
- kubejs/server_scripts/base/tags/items/forge/crops.js
- kubejs/server_scripts/base/tags/items/sereneseasons/seasonal_crops.js
- kubejs/server_scripts/constants/crop_properties.js
- kubejs/server_scripts/constants/dye_sources.js
> Thermal Integration Pass Two

- kubejs/server_scripts/base/recipes/thermal/brewer.js
- kubejs/startup_scripts/base/brewing_registry.js
- kubejs/startup_scripts/base/brewing_remove.js
Disabling the prior Thermal imbuer recipes, as I've come to realize that the Ars potions are simply bugged: https://github.com/baileyholl/Ars-Nouveau/issues/782
Adds a bunch of alternate brewing recipes through MoreJS. Tending towards plant based ingredients to get away from the need of a mob farm to make potions. There are plenty of thematic ingredients around to make that happen.
> More brewing options

- kubejs/client_scripts/base/tooltips.js
- kubejs/server_scripts/base/recipes/enigmatica/dye_crushing.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/tags/items/enigmatica/storage/bags.js
- kubejs/server_scripts/constants/armored_mobs.js
- kubejs/server_scripts/constants/crop_properties.js
- kubejs/server_scripts/constants/dye_sources.js
- kubejs/server_scripts/constants/tree_properties.js
- kubejs/server_scripts/constants/wood_properties.js
- kubejs/startup_scripts/base/brewing_registry.js
Assuming Hexerei passes testing
> Re enable hexerei stuff

- kubejs/server_scripts/base/recipes/naturesaura/shaped.js
Reinstate Ancient Plank to Slab recipe. Resolves: #173
> Reinstate Ancient Plank to Slab recipe

- kubejs/server_scripts/constants/crop_properties.js
let's them 'grow' normally in the cloche display
> fix rendering issues with thermal shrooms in cloche

- config/configswapper/expert/config/powah.json5
- config/configswapper/normal/config/powah.json5
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/immersive_engineering.snbt
- config/ftbquests/quests/chapters/occultism.snbt
- config/ftbquests/quests/chapters/powah.snbt
- config/ftbquests/quests/chapters/thermal_series.snbt
- kubejs/assets/powah/lang/en_us.json
- kubejs/client_scripts/base/tooltips.js
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/server_scripts/base/loot_tables/chests/enigmatica/powah_loot_boxes.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/powah/energizing.js
- kubejs/server_scripts/base/recipes/powah/heat_sources.js
- kubejs/server_scripts/base/recipes/powah/liquid_coolants.js
- kubejs/server_scripts/base/recipes/powah/magmatic_fluids.js
- kubejs/server_scripts/base/recipes/powah/shaped.js
- kubejs/server_scripts/base/recipes/powah/solid_coolants.js
- kubejs/server_scripts/base/recipes/thermal/press.js
- kubejs/server_scripts/base/tags/items/thermal/casts.js
- kubejs/server_scripts/functions.js
Quest and quest loot overhaul.
Updated Configs to remove worldgen. Uraninite and Dry Ice are both crafted. 
Adjusted generation rates. Bringing things down a fair bit. 
Adjusted fuels, heat sources, and coolants. Coolants is on hold for now due to a bug making them work in reverse of expectation.
Starter Tier removed entirely. Basic Tier now uses a bit less Gold/Iron, instead using Thermal Series Alloys in places.
Tiny and basic capacitors removed as well. Only 'large' remains and has been renamed accordingly. Higher tier all use this as their base. 
Energizing recipes similarly modified to escape from vanilla material sink, instead sending the player off to Blue Skies for higher tier materials. 
Extra recipes for AE2:
Add one-step inscriber recipes to servo press:
Add Processor creation …
> Powah quest rework

- kubejs/server_scripts/expert/tags/blocks/the_bumblezone/dimension_teleportation.js
hives need this block below them to work for transport
> Placeholder block requirement for Bumblezone in Expert

- kubejs/server_scripts/expert/recipes/lychee/random_block_ticking.js
requires water on four sides, placeholder for uranium processing
> [Expert] Sample recipe for converting blocks while in water.

- config/ftbquests/quests/chapters/getting_started.snbt
- kubejs/server_scripts/base/recipes/eccentrictome/shapeless.js
Resolves #212 and adds several missing books.
> Update Eccentric Tome

- config/ftbquests/quests/chapters/getting_started.snbt
> Update Getting Started Quests

- config/ftbquests/quests/chapters/create.snbt
> Update quest for Create Sails

- kubejs/server_scripts/expert/recipes/enigmatica/replace_input.js
- kubejs/server_scripts/expert/recipes/twilightforest/shaped.js
was getting a cross of 5 source gems in the middle somehow...
> Fix for replace input acting weird for carminite reactor

- kubejs/server_scripts/base/entity_events/spawned/equipment.js
Seems like a timing issue between drones loading their programs into nbt and me reading/checking/writing to nbt.
> fix PNC drones not working

- config/ars_nouveau-server.toml
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/tags/entity_type/friendlyfire/general_protection.js
Also adds more mobs to Friendly Fire blacklist, just in case.
> Remove invalid bone meal recipe

- config/ftbquests/quests/chapters/ars_nouveau.snbt
> Clarify dependencies for Ars Nouveau quests

- config/configswapper/normal/config/Mekanism/generators.toml
> lower mekanism wind generator's max required height to y128

- config/ftbquests/quests/chapters/ars_nouveau.snbt
- kubejs/client_scripts/base/tooltips.js
Re-arranges the chapter slightly and introduces new quests detailing this new storage system.
> Add quests detailing the new Ars Nouveau Bookwyrm Storage System

- config/ftbquests/quests/chapters/ars_nouveau.snbt
Fix to Ars Storage quests before they go live
> Ars Quest clarification

- kubejs/server_scripts/base/tags/blocks/buildinggadgets/blacklists.js
> Set up Blacklist for Building Gadgets

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/immersiveengineering/shaped.js
Resolves https://github.com/EnigmaticaModpacks/Enigmatica9/issues/333
> Fix treated sticks

- kubejs/server_scripts/base/recipes/apotheosis/affix_loot_entries/overworld.js
- kubejs/server_scripts/base/recipes/ars_nouveau/enchanting_apparatus.js
> more create diving shenanigans

- kubejs/server_scripts/expert/recipes/hexerei/shaped.js
- kubejs/server_scripts/expert/recipes/minecraft/shaped.js
there's some, but incredibly rare, apparently. Will need to look into improving worldgen there.
> quick fix for lack of andesite in twilight forest

- kubejs/client_scripts/lang_modifications.js
- kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
Accidentally applied multiplier to other crushing recipes
> correcting issues with mortar and pestle processing

- kubejs/assets/ars_nouveau/lang/en_us.json
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/nomadictents/shaped.js
Cheaper Nomadic Tents
More wall sections crafted per craft and reduced the cost of Tent Canvas.
> E9E Feedback

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/ars_nouveau/crushing.js
- kubejs/server_scripts/base/recipes/create/crushing.js
- kubejs/server_scripts/base/recipes/create/milling.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/immersiveengineering/crusher.js
- kubejs/server_scripts/base/recipes/thermal/pulverizer.js
- kubejs/server_scripts/base/tags/items/forge/sandstone.js
- kubejs/server_scripts/constants/colors.js
> Add recipes for obtaining Niter from Sandstone

- kubejs/server_scripts/base/unification/unify_loot.js
- kubejs/server_scripts/expert/recipes/ae2/shaped.js
- kubejs/server_scripts/expert/recipes/ars_nouveau/shapeless.js
- kubejs/server_scripts/expert/recipes/farmersdelight/cutting.js
Moved Parchment scraping to cutting board because some knives were getting eaten :-\
AE2 quartz knives adjusted to be pre-iron
> Expert Adjustments

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/hexerei.js
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js
Increases default health and armor for a several familiars to help them survive their combat roles
> Buff Occultism and Hexerei Combat Familiars

- config/ftbquests/quests/chapters/chapter_one.snbt
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/thermal.js
- kubejs/server_scripts/base/tags/entity_type/friendlyfire/general_protection.js
- kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
- kubejs/server_scripts/expert/recipes/pneumaticcraft/shapeless.js
- kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
Vortex Tube brought earlier
Transfer Gadget
Friendly Fire protections extended to Ars Nouveau/Ars Elemental critters to prevent accidents in/around one's base.
Universal Sensor moved up to aid in plastic production
Plastic now more generous
> Moar e9e feedback changes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/loot_modifiers/hexerei/remove.js
- kubejs/server_scripts/base/loot_tables/entities/hexerei/animal_fat.js
> Fix Animal Fat Drops

- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/create_expert.snbt
- config/ftbquests/quests/chapters/occultism_expert.snbt
- kubejs/assets/kubejs/lang/en_us.json
- kubejs/client_scripts/base/jei_descriptions.js
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
- kubejs/server_scripts/base/tags/entity_type/enigmatica/mob_spawner_blacklist.js
- kubejs/server_scripts/base/tags/entity_type/spirit/collect_blacklisted.js
- kubejs/server_scripts/base/tags/items/forge/rods.js
- kubejs/server_scripts/expert/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
- kubejs/server_scripts/expert/recipes/create/shaped.js
- kubejs/server_scripts/expert/recipes/hexerei/pestle_and_mortar.js
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/twilightforest/shaped.js
- Ars mobs properly blacklisted from spawners
- Create Tracks simplified to use stone instead of treated wood
- Recipe for the Ore Magnet
- Transformation Powder
- Moonworm Queen
- Red Thread
- Reduce grind time for Trance Blend (hurry up and calm down!!!) and increased output
> E9E Testing - Continued Feedback

- changelogs/CHANGELOG.md
- config/almostunified/unify.json
- config/configswapper/expert/config/quark-common.toml
- config/configswapper/normal/config/quark-common.toml
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/server_scripts/base/loot_tables/blocks/densetrees/dense_logs.js
- kubejs/server_scripts/base/recipes/byg/shaped.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/enigmatica/shapeless.js
- kubejs/server_scripts/base/recipes/minecraft/shapeless.js
- kubejs/server_scripts/base/recipes/minecraft/stonecutting.js
- kubejs/server_scripts/base/recipes/naturesaura/shaped.js
- kubejs/server_scripts/base/recipes/supplementaries/shaped.js
- kubejs/server_scripts/base/tags/blocks/forge/storage_blocks.js
- kubejs/server_scripts/base/tags/items/forge/storage_blocks.js
- Fix many recipe conflicts 
- Dense Trees now drop multiple regular logs, rather than dense logs 
- Storage blocks for crops are now unified. Stonecutter may be used to obtain alternate block types
> recipe conflicts fixes

- kubejs/server_scripts/expert/loot_tables/chests/enigmatica/powah_loot_boxes.js
Remove dielectric casings from powah quest loot
> Remove dielectric casings from powah quest loot

- config/ftbquests/quests/chapters/chapter_three.snbt
- kubejs/server_scripts/expert/recipes/mekanism/reaction.js
- kubejs/server_scripts/expert/recipes/mekanism/shaped.js
- kubejs/server_scripts/expert/recipes/pneumaticcraft/amadron.js
- Aetheric Transmutatoin Chamber recipe adjusted
- Ch3 Quest Loot made a bit less generous
- Reduce energy cost of Echo Shards
- Increase energy cost of Nether Stars
- Fix broken amadron crates
> E9E Continued Feedback fixes

- kubejs/assets/kubejs/lang/en_us.json
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js
- kubejs/server_scripts/base/recipes/gateways/gateways.js
- kubejs/server_scripts/expert/recipes/occultism/ritual.js
- Possessed Skeleton Ritual updated to use gateways.
> E9E Feedback tweaks

- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
disable xp bottles in disenchantment dynamo
> disable xp bottles in disenchantment dynamo

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/ars_nouveau.snbt
- config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
- config/ftbquests/quests/chapters/chapter_two.snbt
- kubejs/assets/byg/lang/en_us.json
- kubejs/assets/kubejs/lang/en_us.json
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/data/byg/worldgen/configured_feature/floating_island1.json
- kubejs/data/byg/worldgen/configured_feature/floating_island2.json
- kubejs/data/byg/worldgen/configured_feature/floating_island3.json
- kubejs/data/byg/worldgen/configured_feature/floating_island4.json
- kubejs/data/byg/worldgen/configured_feature/floating_island5.json
- kubejs/data/byg/worldgen/configured_feature/island_ametrine_clusters.json
- kubejs/server_scripts/base/loot_tables/blocks/byg/emeraldite_ore.js
- kubejs/server_scripts/base/recipes/emendatusenigmatica/shapeless.js
- kubejs/server_scripts/base/recipes/minecraft/stonecutting.js
- kubejs/server_scripts/base/tags/blocks/forge/ores.js
- kubejs/server_scripts/base/tags/items/forge/ores.js
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/occultism/ritual.js
- kubejs/startup_scripts/base/worldgen/byg/remove.js
- kubejs/startup_scripts/item_registry.js
Minor change to the Market. The intent is that by putting it here it'll be more discoverable as quests direct you to look at Mindful Trance recipes for helpful creatures early game
Add limestone conversion, resolving: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/439
Fix Osmium and Tin Raw Ore block crafting: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/441
Fix Emeraldite: #449
Replace Ametrine with Dimensional crystals: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/478
> E9E Feedback Changes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/apotheosis/minibosses/cnb.js
Apply workaround to miniboss: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/481
> Update Sporeling Miniboss data

- changelogs/CHANGELOG.md
- config/jei/recipe-category-sort-order.ini
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/server_scripts/base/recipes/create/mixing.js
- kubejs/server_scripts/base/recipes/occultism/shapeless.js
- kubejs/server_scripts/base/tags/blocks/forge/storage_blocks.js
- kubejs/server_scripts/base/tags/items/forge/storage_blocks.js
- kubejs/server_scripts/expert/recipes/create/shaped.js
- kubejs/server_scripts/expert/recipes/create/shapeless.js
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/minecraft/shaped.js
- Conduit changed again, should be easier as it is more of a joke than anything
- Block of XP now craftable from Ars gems
- Farmers Delight recipes are now covered by Create Mixing. Don't overheat them or they'll burn! https://github.com/EnigmaticaModpacks/Enigmatica9/issues/463
> E9E Cleanup

- changelogs/CHANGELOG.md
- config/configswapper/normal/config/ars_nouveau-common.toml
- config/jei/recipe-category-sort-order.ini
- kubejs/server_scripts/base/tags/items/industrialforegoing/laser_lens.js
- kubejs/server_scripts/base/tags/items/mekanism/colorable.js
- kubejs/server_scripts/expert/recipes/spirit/soul_engulfing.js
- kubejs/server_scripts/normal/recipes/mekanism/painting.js
- kubejs/server_scripts/normal/recipes/mekanism/pigment_extracting.js
- kubejs/startup_scripts/structure_modifications.js
- Ars Nouveau Potion Melder now has the same buffed output as Expert mode (2 melded potions out for every 2 potions in)
- Rockwool may now be colored by the Mekanism Painter https://github.com/EnigmaticaModpacks/Enigmatica9/issues/492
> Normal mode updates

- kubejs/server_scripts/expert/recipes/the_bumblezone/armor_upgrade.js
In reference to https://github.com/EnigmaticaModpacks/Enigmatica9/pull/493#issuecomment-1637283744
> Further changes to bee armor

- kubejs/server_scripts/expert/entity_events/spawned/spirit_spawner.js
- kubejs/server_scripts/expert/recipes/twilightforest/shaped.js
- kubejs/server_scripts/force_reload.js
With this, and prior changes that could be pushed to develop already, we should be ready to update to KubeJS 6.1 and addons.
> Final changes for 6.1 Compatibility

- changelogs/CHANGELOG.md
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/server_scripts/base/tags/mob_effect/mekanism/speed_up_blacklist.js
- kubejs/server_scripts/expert/player_events/armor_sets.js
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/mekanism/shaped.js
- Correct Armor Set script to only run in Expert
- Blacklist certain effects from Inhalation unit removal
- Re-enable the Inhalation Purification unit for Expert
> Armor set fixes

- kubejs/server_scripts/expert/loot_tables/chests/enigmatica/remove.js
Remove Experience Nuggets from drop tables
> Remove Experience Nuggets from drop tables

- config/configswapper/expert/config/restrictedportals-common.toml
> Update Restricted Portals

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/minecraft/stonecutting.js
Source Gems may now be stonecut to different varieties
> source gem stonecutting

- kubejs/server_scripts/expert/tags/enchantment/crystalline_flower.js
fix yeeted enchants showing up in crystalline flower
> fix yeeted enchants showing up in crystalline flower

- changelogs/CHANGELOG.md
- kubejs/assets/railways/lang/en_us.json
- kubejs/server_scripts/normal/recipes/superiorshields/shaped.js
> Fix Enchanter's Shield recipe

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/occultism.snbt
- config/ftbquests/quests/chapters/occultism_expert.snbt
Fix Djinn Machine Operator Quest
> Fix Djinn Machine Operator Quest

- kubejs/server_scripts/expert/recipes/occultism/pentacles.js
Fix missing candles in Gythia's
> Fix missing candles in Gythia's

- changelogs/CHANGELOG.md
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/dimensional_geode.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/emerald_geode_dripstone_caves.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/emerald_geode_hills_high.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/emerald_geode_hills_low.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/emerald_geode_swamp.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/fluorite_geode.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/fluorite_geode_nether.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/ocean_geode.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/redstone_geode.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/sulfur_geode_air.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/sulfur_geode_nether.json
- config/configswapper/expert/config/emendatusenigmatica/deposit/geodes/sulfur_geode_water.json
- kubejs/server_scripts/base/recipes/lychee/block_interacting.js
- remove more uranium, osmium, and lead ores
- Crystal Cluster blocks may now be converted to Budding via Right Click Interaction
- Cooldown for Right Click Interactions has been reduced.
> E9E Feedback Fixes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/farmersdelight/cutting.js
Allow therium/subzero to be broken down into the crystals
> Allow therium/subzero to be broken down into the crystals

- changelogs/CHANGELOG.md
- kubejs/server_scripts/normal/recipes/create/crushing.js
- kubejs/server_scripts/normal/unification/unify_ore_processing.js
Somehow overlooked these recipes in the Kube overhaul
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/539
> Fix broken ore processing recipes

- kubejs/server_scripts/expert/recipes/ars_nouveau/glyph.js
- Make Phantom's Grasp accessible
> E9E Improvements

- config/ftbquests/quests/chapters/building.snbt
- kubejs/server_scripts/expert/recipes/ars_nouveau/enchantment.js
Allow going up to mana regen VII on the Enchanting Apparatus
> Mana Regen crafting recipes

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/pneumaticcraft_repressurized_expert.snbt
- kubejs/client_scripts/lang_modifications.js
- kubejs/server_scripts/expert/recipes/minecraft/stonecutting.js
- kubejs/server_scripts/normal/unification/unify_ore_processing.js
- Air Grates and Andesite Scaffolding are craftable again in expert
- Another correction to ore processing: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/539
> General fixes

- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/client_scripts/expert/jei_hide_fluids.js
- kubejs/server_scripts/base/recipes/byg/shaped.js
- kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
- kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
- kubejs/server_scripts/expert/recipes/hexerei/shaped.js
- kubejs/server_scripts/normal/recipes/byg/shaped.js
Forgot to push before merge https://github.com/EnigmaticaModpacks/Enigmatica9/pull/553
> Expert improvements

- kubejs/server_scripts/expert/recipes/naturesaura/shaped.js
Missing recipe from https://github.com/EnigmaticaModpacks/Enigmatica9/pull/567#issue-1832929837
> Expert Creational Catalyst

- kubejs/client_scripts/base/emi_material_unification.js
overzealous regex strikes again
> fix missing nature's aura equipment

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
> [Expert] Cheaper Warp Relay

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/hexerei.snbt
- config/ftbquests/quests/chapters/hexerei_expert.snbt
Hexerei quests now accept any broom. https://github.com/EnigmaticaModpacks/Enigmatica9/pull/619
> Broom quests

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/loot_tables/blocks/hexerei/mahogany_leaves.js
- kubejs/server_scripts/base/loot_tables/blocks/hexerei/willow_leaves.js
- kubejs/server_scripts/base/loot_tables/blocks/hexerei/witch_hazel_leaves.js
Fix for Ancient Leaves not dropping the intended drops.
> Leaf fixes

- changelogs/CHANGELOG.md
- kubejs/assets/emi/index/stacks/emi_added_items.json
- kubejs/client_scripts/base/emi_add_items.js
- kubejs/server_scripts/expert/recipes/ars_nouveau/enchantment.js
- kubejs/server_scripts/expert/recipes/industrialforegoing/dissolution_chamber.js
- kubejs/server_scripts/expert/recipes/industrialforegoing/laser_drill_ore.js
Ars Nouveau Armor tiers now show in EMI, allowing easier comparison of tiers. 
Mana Boost may now be upgraded up to VII in the Mana Enchanter
Expert end game process for making dragon heads/eggs/scales has changed.  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/616
Heads:
Eggs:
Scales:
> General enhancements

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/ars_nouveau.snbt
- config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
- config/ftbquests/quests/chapters/chapter_one.snbt
- config/ftbquests/quests/chapters/hexerei.snbt
- config/ftbquests/quests/chapters/hexerei_expert.snbt
- config/ftbquests/quests/chapters/storage.snbt
- config/ftbquests/quests/chapters/storage_expert.snbt
- kubejs/client_scripts/base/jei_descriptions.js
- kubejs/server_scripts/base/tags/items/forge/glyphs.js
Fix typos in quests
- https://github.com/EnigmaticaModpacks/Enigmatica9/issues/631
- https://github.com/EnigmaticaModpacks/Enigmatica9/issues/629
- https://github.com/EnigmaticaModpacks/Enigmatica9/issues/628
- https://github.com/EnigmaticaModpacks/Enigmatica9/issues/627
Add missing glyphs to glyph recycling https://github.com/EnigmaticaModpacks/Enigmatica9/issues/630
> E9 General Enhancements

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/immersiveengineering/bottling_machine.js
- kubejs/server_scripts/base/recipes/thermal/hive_extractor.js
-   IE's Bottling Machine may now make honey bottles. 
-   Thermal's Hive Hopper now extracts Bumblezone Honey.
> Honey Improvements

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/ars_nouveau/enchanting_apparatus.js
Allow Leather to be upgraded to Ars Armor
> Allow Leather to be upgraded to Ars Armor

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/ars_nouveau.snbt
- config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
- kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
Reduced Sculk requirements for end game
Fixed typos
> General improvements

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/pneumaticcraft/pressure_chamber.js
-   Fixed uncraftable range 3 upgrade for mining gadgets.  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/675
> Fix for uncraftable range upgrade

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/items/the_bumblezone/bee_queen.js
The Queen Bee will no longer ask for Golden Leaves https://github.com/EnigmaticaModpacks/Enigmatica9/issues/694
> bee trades

- changelogs/CHANGELOG.md
- config/Mekanism/client.toml
- kubejs/client_scripts/lang_modifications.js
- kubejs/server_scripts/base/loot_tables/entities/occultism/afrit_wild.js
- kubejs/server_scripts/expert/recipes/lychee/random_block_ticking.js
- kubejs/server_scripts/expert/recipes/mekanism/nucleosynthesizing.js
- kubejs/server_scripts/expert/recipes/powah/energizing.js
-   [Expert] Infused Ender Pearls now craft 4 at a time, making it faster to fill the cores needed for end game.
-   Occultism Wild Afrit now drops more Essence per kill
- [Expert] Reduce the amount of Aetherium required to make Aetheric Brass and Infinity Tools
- [Expert] Fixed some lingering references to Compressed Iron https://github.com/EnigmaticaModpacks/Enigmatica9/issues/702
-   [Expert] The Tree of Life now produces significantly more Aura each day
> E9E Feedback improvements

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/entity_type/occultism/soul_gem_deny_list.js
Blacklist Ars familiars from Occultism's soul gem: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/705
> Anti familiarity

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
Fix broken Necrotic Focus recipe https://github.com/EnigmaticaModpacks/Enigmatica9/issues/719
> fix necrotic focus

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/tags/biome/ae2/has_meteorites.js
disable ae2 meteorites for realz https://github.com/EnigmaticaModpacks/Enigmatica9/issues/722
> disable ae2 meteorites for realz

- changelogs/CHANGELOG.md
> Expert recipes for new items

- automation/start-automated-server.sh
> Fix start-automated-server.sh

- changelogs/CHANGELOG.md
- config/configswapper/expert/config/naturesaura-common.toml
- config/configswapper/normal/config/naturesaura-common.toml
disable explosions from low Aura
> disable explosions from low Aura

- changelogs/CHANGELOG.md
- kubejs/server_scripts/normal/recipes/enigmatica/remove.js
- kubejs/server_scripts/normal/unification/unify_ore_processing.js
fix e9 pulverizer recipes https://github.com/EnigmaticaModpacks/Enigmatica9/issues/749
> fix e9 pulverizer recipes

- config/ftbquests/quests/chapters/applied_energistics_2_expert.snbt
> minor quest clarification

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/create_expert.snbt
- Clarify Create waterwheel quest https://github.com/EnigmaticaModpacks/Enigmatica9/issues/760
> Clarify waterwheel quest

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
-   [Expert] The first Tree of Life quest now warns the player how large the structure is and that it will delete blocks in the area.
> quest clarification

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/lychee/block_interacting.js
- kubejs/server_scripts/expert/recipes/powah/energizing.js
- kubejs/server_scripts/expert/structures/integrated_stronghold/portal_room.js
-   [Expert] Infused Ender Pearls now require Aetheric Brass to craft 
-   [Expert] It should no longer be possible to go to the End using a vanilla portal
> progression fixes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/powah/energizing.js
missed commit https://github.com/EnigmaticaModpacks/Enigmatica9/pull/763
> missed commit

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
- config/ftbquests/quests/chapters/chapter_three.snbt
- config/ftbquests/quests/chapters/chapter_two.snbt
-   [Expert] Quests added to draw attention to Modular Routers as a power transfer method
> quest updates

- changelogs/CHANGELOG.md
- kubejs/server_scripts/normal/recipes/enigmatica/remove.js
- [Normal] Remove unwanted thermal compat recipes https://github.com/EnigmaticaModpacks/Enigmatica9/issues/767
> remove unwanted thermal compat recipes

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
-   [Expert] Spell Turret quest in Chapter 1 now named Lingering Absorber Automation to help with discoverability
> quest tweak

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/ars_nouveau/crushing.js
- kubejs/server_scripts/base/recipes/create/crushing.js
- kubejs/server_scripts/base/recipes/immersiveengineering/crusher.js
- kubejs/server_scripts/base/recipes/thermal/pulverizer.js
- kubejs/server_scripts/expert/recipes/industrialforegoing/laser_drill_ore.js
-   Crushing Blizz Rods and Basalz Rods now gives Certus and Fluorite respectively
> Crystal improvements

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
- kubejs/server_scripts/expert/loot_tables/entities/twilightforest/death_tome.js
- kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
- kubejs/server_scripts/expert/recipes/minecraft/shaped.js
-   [Expert] End Crystals are now more expensive. This is to help signal to the player that repeatedly summoning and killing the dragon is not the route to take for eggs as they're craftable.  
-   [Expert] Spawner Core Shells are now less expensive, crafting in batches of four
> Core adjustment

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_three.snbt
-   [Expert] Fix Heart of the Sea quest  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/780
> heart of the sea fix

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/industrialforegoing/dissolution_chamber.js
machine doesn't appear to accept tag inputs for fluid :(
> Bottle o Enchanting recipes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/create/cutting.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/immersiveengineering/sawmill.js
- kubejs/server_scripts/base/recipes/thermal/sawmill.js
- kubejs/server_scripts/expert/recipes/immersiveengineering/sawmill.js
- kubejs/server_scripts/expert/recipes/thermal/sawmill.js
- kubejs/server_scripts/normal/recipes/mekanism/sawing.js
-   Bookshelves may be processed in a saw mill to extract books   https://github.com/EnigmaticaModpacks/Enigmatica9/issues/790
-   [Expert] Dimensional Storage Crystals may now be produced in a Thermal saw
> Books from Bookshelves

- kubejs/server_scripts/expert/recipes/thermal/sawmill.js
> remove duplicate sawing recipes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/loot_tables/entities/twilightforest/questing_ram_rewards.js
- kubejs/server_scripts/expert/loot_tables/entities/twilightforest/snow_queen.js
-   [Expert] The Snow Queen and Questing Ram now drop Budding versions of their crystal resource to nudge players towards growing more.
> Snow Queen and Questing Ram loot update

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/mekanism/enriching.js
Remove conflicting Sulfur Enriching recipe
> Remove conflicting Sulfur Enriching recipe

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
> Remove ore centrifuge recipes

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/tools.snbt
- config/ftbquests/quests/chapters/tools_expert.snbt
-   Excavator quest now accepts any tier of excavator/hammer  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/826
> Fix Excavator Quests

- config/ftbquests/quests/chapters/chapter_one.snbt
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/833
> more quest tweaks

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/create_expert.snbt
- kubejs/assets/create/lang/en_us.json
- kubejs/client_scripts/lang_modifications.js
- [Expert] Renamed Andesite Doors to Compressed Stone Doors https://github.com/EnigmaticaModpacks/Enigmatica9/issues/836
-   New quests added for Mechanical Roller and Elevator Pulley
> Rename Andesite Doors

- config/ftbquests/quests/chapters/chapter_one.snbt
more quest clarifications in ch1
> more quest clarifications

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/loot_tables/blocks/ae2/clusters.js
- kubejs/server_scripts/base/loot_tables/blocks/byg/clusters.js
- kubejs/server_scripts/base/loot_tables/blocks/emendatusenigmatica/clusters.js
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/base/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/enigmatica/dust_crushing_tiers.js
- kubejs/server_scripts/expert/recipes/lychee/lightning_channeling.js
- [Expert] Remove chance of failure when using lightning crafting to do final tier of ore processing https://github.com/EnigmaticaModpacks/Enigmatica9/issues/845
-   [Expert] Remove broken recipes for Iesnium Dust
-   Slight buff to all crystal cluster drop rates
-   Slight buff to Charcoal > Coal conversion rate with Nature's Aura 
-   Remove unintended Osmium ore recipe from Pulverizer
> crushing and processing

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
- kubejs/client_scripts/base/jei_descriptions.js
- kubejs/client_scripts/expert/jei_descriptions.js
- kubejs/client_scripts/normal/jei_descriptions.js
- kubejs/server_scripts/base/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/enigmatica/dust_crushing_tiers.js
- kubejs/server_scripts/expert/recipes/mekanism/metallurgic_infusing.js
- [Expert] Golden Apples, Golden Carrots, and Glistering Melons all have a new recipe in Mekanism
-   Golden Apples, Golden Carrots, and Glistering Melons recipe in Nature's Aura has had the time/aura cost normalized across the board. Apples and carrots now craft significantly faster while melons will be a bit slower.
-  [Expert] Fixed typo in Nomadic Tent quest https://github.com/EnigmaticaModpacks/Enigmatica9/issues/856
-   [Expert] Attempt to clarify EMI description for Ars Nouveau fruit https://github.com/EnigmaticaModpacks/Enigmatica9/issues/852
> Golden Fruit

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
Remove random electrum recipe that appeared
> Remove random electrum recipe that appeared

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/items/ars_nouveau/interact_jar_blacklist.js
- Blacklist Spellbooks from being inserted into Containment Jars
> Blacklist Spellbooks from being inserted into Containment Jars

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/mekanism/reaction.js
-   [Expert] Reduced processing time for Enderium
> Reduce processing time for Enderium

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
Remove wool from Windmill quest https://github.com/EnigmaticaModpacks/Enigmatica9/issues/678#issuecomment-1958193461
> Really remove wool from Create Quests

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
Reverts EnigmaticaModpacks/Enigmatica9#874
> Revert "Really remove wool from Create Quests"

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/create_expert.snbt
-   [Expert] Remove reference to wool in Create Windmill quest https://github.com/EnigmaticaModpacks/Enigmatica9/issues/678#issuecomment-1958193461
> Remove Wool from Sails

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/immersive_engineering_expert.snbt
-   [Expert] Removed disabled tank from IE quest chapters
> Removed disabled tank from IE quest chapters

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/occultism/ritual.js
-   [Expert] Market recipe now uses all 5 archwood saplings to help avoid confusion with the recipe
> Update market recipe

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_three.snbt
- [Expert] Fix for the honey compass quest for the Ancient City not completing https://github.com/EnigmaticaModpacks/Enigmatica9/issues/882
> Fix Honey Compass quest not completing

- kubejs/server_scripts/base/loot_tables/blocks/ae2/clusters.js
- kubejs/server_scripts/expert/recipes/ars_nouveau/patchouli_safe_remove.js
Fixing a few errors in the logs related to recipe creation.
> Error cleanup

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
- config/ftbquests/quests/chapters/occultism.snbt
- config/ftbquests/quests/chapters/occultism_expert.snbt
- kubejs/server_scripts/base/tags/entity_type/occultism/familiars.js
- kubejs/server_scripts/expert/recipes/the_bumblezone/bz_bee_queen_trades.js
-   Occultism Familiars quest now relies on seeing a familiar instead of getting the advancement https://github.com/EnigmaticaModpacks/Enigmatica9/issues/868
> fix occultism familiar quest

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/entity_type/create/ignore_seat.js
-   Blacklisted the Quest Ram from Create Seats to avoid a dupe bug https://github.com/EnigmaticaModpacks/Enigmatica9/issues/777
> blacklist quest ram from create seats

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/pneumaticcraft/shapeless.js
-   [Expert] Omni Hoppers can now be crafted earlier.
> Omni Hoppers

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/ars_nouveau/caster_tome.js
-   Adds several community suggested Caster Tomes to loot! https://github.com/EnigmaticaModpacks/Enigmatica9/issues/198
> Caster Tomes

- changelogs/CHANGELOG.md
- config/configswapper/expert/config/apotheosis/adventure.cfg
- config/configswapper/normal/config/apotheosis/adventure.cfg
- config/ftbquests/quests/chapters/ars_nouveau.snbt
- config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
- config/ftbquests/quests/chapters/villagers_expert.snbt
- kubejs/server_scripts/base/entity_events/spawned/custom_rituals.js
- kubejs/server_scripts/base/recipes/apotheosis/affix_loot_entries/twilight_forest.js
- kubejs/server_scripts/constants/ritual_effects.js
- kubejs/server_scripts/expert/recipes/immersiveengineering/squeezer.js
- kubejs/server_scripts/expert/recipes/lychee/block_interacting.js
- kubejs/server_scripts/expert/recipes/mekanism/nucleosynthesizing.js
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
- kubejs/server_scripts/expert/recipes/thermal/pulverizer.js
- Correct quest description for bookwyrm familiars https://github.com/EnigmaticaModpacks/Enigmatica9/issues/909
- Fixed an issue with Gateways crashing the game if used in a Compact Machine https://github.com/EnigmaticaModpacks/Enigmatica9/issues/911
-   [Expert] Teleportation rituals now inform the player why they failed if executed in the wrong dimension
-   [Expert] Mekanism tanks may no longer be upgraded in world as higher tiers are meant to be disabled
-   [Expert] Motes now require regular potions instead of lingering potions
> Small fixes

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/items/forge/stripped_logs.js
- kubejs/server_scripts/base/tags/items/forge/stripped_wood.js
-   Fix missing stripped log/wood tags https://github.com/EnigmaticaModpacks/Enigmatica9/issues/914
> Fix Stripped Logs/Wood tags

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/tags/blocks/minecraft/mineable.js
-   Add default tool for Enigmatic Unity and Energy Meters
> default tools

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/thermal/crystallizer.js
-   [Expert] Adjust ratio of dimension shards to metal crystals
> Moar Crystals!

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/create_expert.snbt
- Clarify Create quests for straws https://github.com/EnigmaticaModpacks/Enigmatica9/issues/697
> Clarify create quests for straws

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/ars_nouveau.snbt
- config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
-   Added entries for Amethyst Golems in Ars Nouveau's quests https://github.com/EnigmaticaModpacks/Enigmatica9/issues/927
> Ars Nouveau quest updates

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/loot_tables/chests/enigmatica/aura_leaves.js
Apparently it's too small to really notice, so people assume they don't work :( Massive buff!
> Buff Aura Infusion

- changelogs/CHANGELOG.md
- kubejs/client_scripts/constants/jei_hidden_disabled.js
- kubejs/server_scripts/expert/recipes/enigmatica/remove.js
-   [Expert] Disable a coal gen that was missed
> dirty coal

- changelogs/CHANGELOG.md
- kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
- kubejs/server_scripts/expert/recipes/thermal/crystallizer.js
- kubejs/startup_scripts/fluid_registry.js
-   [Expert] Processing Metal Shards now has an extra step involving the creation and use of Lacunar Acid https://github.com/EnigmaticaModpacks/Enigmatica9/issues/967
> Shard Processing

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/thermal_series.snbt
- kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_emerald.json
- kubejs/server_scripts/expert/recipes/apotheosis/bosses/overworld.js
- kubejs/server_scripts/expert/recipes/apotheosis/bosses/the_bumblezone.js
- kubejs/server_scripts/expert/recipes/apotheosis/bosses/the_end.js
- kubejs/server_scripts/expert/recipes/apotheosis/bosses/the_nether.js
- kubejs/server_scripts/expert/recipes/apotheosis/bosses/twilight_forest.js
- kubejs/server_scripts/normal/recipes/apotheosis/bosses/overworld.js
- kubejs/server_scripts/normal/recipes/apotheosis/bosses/the_bumblezone.js
- kubejs/server_scripts/normal/recipes/apotheosis/bosses/the_end.js
- kubejs/server_scripts/normal/recipes/apotheosis/bosses/the_nether.js
- kubejs/server_scripts/normal/recipes/apotheosis/bosses/twilight_forest.js
-   [Normal] Correct Thermal's quests regarding Fluxducts https://github.com/EnigmaticaModpacks/Enigmatica9/issues/969
- Add Aloe to the market https://github.com/EnigmaticaModpacks/Enigmatica9/issues/971
- Fix missing apotheosis bosses https://github.com/EnigmaticaModpacks/Enigmatica9/issues/970
> All the fixins

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- kubejs/server_scripts/normal/recipes/minecraft/shaped.js
- fix furnace being uncraftable for some reason despite a recipe existing
> fix furnace being uncraftable for some reason despite a recipe existing

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/applied_energistics_2.snbt
- config/ftbquests/quests/chapters/applied_energistics_2_expert.snbt
Fixes https://github.com/EnigmaticaModpacks/Enigmatica9/issues/990
> ae2 link update

- changelogs/CHANGELOG.md
- config/ftbquests/quests/chapters/chapter_one.snbt
- kubejs/server_scripts/expert/recipes/naturesaura/altar.js
-   [Expert] Golden Mallet is now unbreakable.
> Golden Mallet

- changelogs/CHANGELOG.md
- kubejs/server_scripts/base/recipes/enigmatica/remove.js
- Fix issue with IE crusher giving wrong outputs for Lapis. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/1000
> Smol Fixes

- config/cable_facades-common.toml
- kubejs/server_scripts/expert/recipes/enigmatica/replace_input.js
adjusts wrench recipe for expert, adds a few extra blocks to the config
> Cable Facades integration
