config/explorerscompass-common.toml, kubejs/client_scripts/base/jei_descriptions.js, kubejs/server_scripts/base/recipes/explorerscompass/shaped.js
Main goal with this is to help with Blue Skies progression. Therefore all other structures have been disabled from it. 
Also sets the recipe to use blue skies materials. 
And sets a description for whenever that feature gets fixed in KubeJS :D
=> Limit Explorer's Compass

config/configswapper/expert/config/naturesaura-common.toml, config/configswapper/normal/config/naturesaura-common.toml
Set up NA Config Swapper
Set desired aura in various dimensions
Move aura bar to lower right so it's not constantly overlapped by other things. 
Expert only:
Disable Ore Generator effect in config (recipe still needs to be removed)
Override Shooting Mark projectiles. 
- Disables most projectiles. 
- Reduces value of Ender Pearls and XP bottles as those are too good for how common they are. 
- Add Ars Nouveau Spell projectiles at a 1:200 Source to Aura ratio. Probably not final. 
- Will eventually add Mana bursts to this too, whenever Botania ports. 
- Other 'projectile' ideas welcome.
=> Nature's Aura Configs

config/almostunified/unify.json, kubejs/server_scripts/base/recipes/create/cutting.js, kubejs/server_scripts/base/recipes/enigmatica/crushing.js, kubejs/server_scripts/base/recipes/enigmatica/dye_crushing.js, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/base/recipes/enigmatica/shapeless.js, kubejs/server_scripts/base/recipes/hexerei/pestle_and_mortar.js, kubejs/server_scripts/base/recipes/immersiveengineering/cloche.js, kubejs/server_scripts/base/recipes/immersiveengineering/sawmill.js, kubejs/server_scripts/base/recipes/mekanism/sawing.js, kubejs/server_scripts/base/tags/items/byg/dyes.js, kubejs/server_scripts/base/tags/items/enigmatica/dye_source.js, kubejs/server_scripts/constants/dye_sources.js, kubejs/server_scripts/constants/wood_properties.js, kubejs/server_scripts/expert/recipes/immersiveengineering/blastfurnace_fuel.js
General cleanup to get back to using `Item.of()` and `Ingredient.of()` now that they seem to be working correctly (for the most part). Trying to make things more readable, overall. 
Also brings dye crushing and sawing to Create, as well as dye crushing to Hexerei.
=> Script cleanup

config/jei/world/local/New_World__3/bookmarks.ini, kubejs/startup_scripts/worldgen_add.js, kubejs/startup_scripts/worldgen_remove.js
Will be more useful when EE is ready, but at least it answers the question of how to disable BlueSkies ores.
=> Setup script to be able to disable ore gen

kubejs/client_scripts/expert/jei_descriptions.js, kubejs/server_scripts/expert/block_events/disable_blueskies_portals.js
Disabling as they always route back to the Overworld, which won't work with expert progression.
=> [Expert] Disable Blue Skies portals

automation/settings.ps1
=> Add Missing config to CF downloads, to allow Custom Main Menu to work.

kubejs/server_scripts/base/entity/spawned/equipment.js, kubejs/server_scripts/constants/armored_mobs.js
Script was running again if the mob was picked up and put back down with a soul gem.
=> Prevent equipment script from running twice on the same mob

kubejs/server_scripts/constants/armored_mobs.js
Arch Druids (rare subtype of Twilight Forest Skeleton Druids) now have a chance to proc a reactive poison cloud when struck.
=> Give Archdruids some poison spray

config/configswapper/expert/config/quark-common.toml, kubejs/server_scripts/base/entity/spawned/equipment.js, kubejs/server_scripts/base/loot_tables/entities/twilightforest/death_tome.js, kubejs/server_scripts/constants/armored_mobs.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/drowned.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/husk.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/iron_golem.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/zombie.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/zombie_villager.js, kubejs/server_scripts/expert/loot_tables/entities/minecraft/zombified_piglin.js, kubejs/server_scripts/expert/loot_tables/entities/twilightforest/carminite_golem.js, kubejs/server_scripts/expert/loot_tables/entities/twilightforest/kobold.js, kubejs/server_scripts/expert/loot_tables/entities/twilightforest/questing_ram_rewards.js, kubejs/server_scripts/functions.js
Disables ingots dropping from any mobs. (Vanilla mobs done, need to check other mods)
Disables Mending entirely. Between Life Mending and Aura Mend, I think those cover things pretty well. Eventually Botania (and Botania Additions) will also allow repairing anything with Mana.
=> [Expert] Disable Mending and Ingot drops from mobs

kubejs/server_scripts/base/loot_tables/entities/creeperoverhaul/cave_creeper.js, kubejs/server_scripts/base/loot_tables/entities/quark/stoneling_carry.js
Default Stonelings are basically an all in one mob farm, dropping diamonds, emeralds, gold, iron, and more... Changed to make them a little less crazy.
Remove ore drops from Cave Creepers, replacing it with a small chance for glow lichen instead.
=> Adjust Cave Creeper and Stoneling Loot Tables

kubejs/server_scripts/base/recipes/ars_nouveau/shapeless.js, kubejs/server_scripts/base/recipes/enigmatica/dye_crushing.js, kubejs/server_scripts/base/recipes/enigmatica/shapeless.js, kubejs/server_scripts/base/tags/items/forge/dyes.js, kubejs/server_scripts/constants/dye_sources.js
Fixes issue with empty tags being used to create dye recipes. Not certain what is causing empty tags to have a `minecraft:barrier`, but it breaks the `.isEmpty()` check on Ingredients...
Also adds re-adds missing dye mixing recipes and adds some non vanilla ones (green and brown). Fixes #138
=> Reinstate Dye Mixing Recipes

kubejs/server_scripts/base/entity/spawned/equipment.js
the `toString()` part of this didn't actually fix the issue, it just prevented the script from working.
KubeJS Forge 1902.6.0-build.128 fixed the underlying issue that had caused it to break in the first place. Spawns are now working again.
=> Mobs will spawn with custom random equipment again

kubejs/server_scripts/base/tags/items/blue_skies/ingots.js
`blue_skies:ingots/falsite` tag is required to apply falsite to tools to boost their durability
=> Fix Blue Skies Tool Box mechanic

config/configswapper/expert/config/naturesaura-common.toml, config/configswapper/normal/config/naturesaura-common.toml, config/naturesaura-common.toml, kubejs/client_scripts/base/jei_descriptions.js, kubejs/server_scripts/base/recipes/lychee/block_interacting.js, kubejs/server_scripts/base/tags/blocks/ars_nouveau/golem.js, kubejs/server_scripts/base/tags/items/ars_nouveau/golem.js
Allows Certus Quartz to be boosted and harvested by AN's Amethyst Golem
Converts all Nature's Aura Right Click interactions for the Infused Iron Pick to be Lychee recipes instead. This way they show in JEI and are more easily discoverable. This also allows more granular control of the durability cost of certain conversions.
Create high durability cost recipe for AE2 budding certus, allowing one to upgrade from a basic block of certus quartz up to a flawless budding block.
=> Allow Ars Nouveau's Amethyst Golems to harvest Certus Quartz

kubejs/server_scripts/base/entity_events/spawned/equipment.js
Just makes a nice thematic compat since both come from vanilla spawners. Adds a pretty overlay to the mobs and prevents all the extra stuff added to world-gen mobs from appearing on them as well.
Not quite functional yet as there's a small bug in PNC that's leading to a timing issue (they don't spawn with the PNC tags, they get it a moment later instead). Desht is looking into that, however, and this won't break anything in the meantime.
=> Convert PNC spawned mobs to Spirit Corrupted mobs

config/byg/trades.json5, config/ftbquests/quests/chapters/villagers.snbt, kubejs/assets/kubejs/lang/en_us.json
We can use BYG to add trades to villagers too. All I've added at this point is rabbit's feet to butchers. Prettier just makes this one like like _everything_ changed
Since Just Enough Professions didn't seem to work well in e6 on servers, I figure this is a decent alternative to get the information to the player while also offering some nice loot rewards.
=> New Quest Chapter for Villagers detailing their workstation and giving a brief rundown of the sorts of trades they have

config/supplementaries-common.toml
This was effectively breaking Nature's Aura Shooting Mark
=> disable Supplementaries feature to teleport Dispensers that launch Ender Pearls

config/supplementaries-common.toml
It's causing apotheosis to lootify them and that makes them a mess to farm.
=> Disable wearable shulker shells

kubejs/server_scripts/base/recipes/ars_nouveau/enchanting_apparatus.js
Grouped up by relative armor strength. So, armors roughly similar to Diamond may all be converted to Battlemage's Armor, for example. 
Resolves #277
=> Allow more armor types to be upgraded to Ars Nouveau armors

config/ftbquests/quests/chapters/industrial_foregoing.snbt, kubejs/server_scripts/base/loot_tables/chests/enigmatica/industrial_foregoing_loot_boxes.js
Loot tables were missing entirely, oops! Also adds loot to some quests that had none previously.
=> Fix missing loot in Industrial Foregoing quest chapter

config/configswapper/expert/serverconfig/enigmaticunity-server.toml, config/configswapper/normal/serverconfig/enigmaticunity-server.toml
During testing, I started to notice that one of the big bottlenecks to the system was that Source relays couldn't transfer fast enough to keep up with the 1000 source per second usage of the previous configs. 
Since Source is primarily meant to be the activator here, or carrier, I'm dramatically reducing the amount pulled per operation from 1000 source to 50. 
This makes it easier for a network of relays to keep up with the Source draw, meaning more crystals can be run off of a single network.
This also pretty heavily boosts the 'worth' of Source in terms of FE, but still keeps Aura as the dominant FE producer per tick. Aura also received a buff to slightly slow down the rate at which it is drained. 
Overall the total FE/t for each tier remains the same. They're just more efficient and …
=> Rebalance Enigmatic Unity power conversion

config/configswapper/expert/config/emendatusenigmatica/material/gold.json, config/configswapper/normal/config/emendatusenigmatica/material/gold.json, config/ftbquests/quests/chapters/chapter_one.snbt, kubejs/client_scripts/base/jei_descriptions.js, kubejs/server_scripts/base/tags/blocks/ars_nouveau/gravity_blacklist.js, kubejs/server_scripts/base/tags/blocks/ars_nouveau/whirlisprig.js, kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/enigmatica/replace_input.js, kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js, kubejs/server_scripts/expert/recipes/twilightforest/hollow_hills.js
- Fix rates from crushing ore in mortar and pestle. Was unintentionally low due to other changes.
- Remove Raw Block > metal block processing which allowed early access to iron
- Add note to Liveroot on where to find it
- Allow liveroot to be harvested by whirlisprigs
- Magebloom Seeds have a cheaper secondary recipe once the first has been made
- Hoppers and Buckets now use Tin Ingots instead of Plates. You also get 4 free hoppers from early ore processing quests. Yay!
- Gold Ore harvest level reduced to simplify tool progression.
=> Expert Playtest feedback fixes

changelogs/CHANGELOG.md, kubejs/server_scripts/base/loot_tables/blocks/quark/blossom_leaves.js
Only getting 1-4 saplings from a huge tree isn't great when you're trying to farm them.
=> Increase drop rate of saplings from quark trees

changelogs/CHANGELOG.md, kubejs/server_scripts/normal/recipes/powah/shaped.js
Wrong type of carminite was used.
=> Fix Powah Reactor recipe

kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/create/filling.js, kubejs/server_scripts/expert/recipes/create/mixing.js, kubejs/server_scripts/expert/recipes/enigmatica/blasting.js, kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js, kubejs/server_scripts/expert/recipes/immersiveengineering/bottling_machine.js, kubejs/server_scripts/expert/recipes/thermal/bottler.js
Nickel should now be available before Iron
Bringing back Secondaries from Sulfuric Acid processing, but at a lower rate than originally.
Moved similar recipes to Mixing from Filling for Create.
=> Fix for unobtainable nickel

config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/powah_expert.snbt, kubejs/client_scripts/lang_modifications.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/ars_nouveau.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/cnb.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/hexerei.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/thermal.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/twilightforest.js, kubejs/server_scripts/constants/metal_properties.js, kubejs/server_scripts/constants/minibosses.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js, kubejs/server_scripts/expert/recipes/modularrouters/shaped.js, kubejs/server_scripts/expert/recipes/powah/shaped.js, kubejs/server_scripts/expert/recipes/thermal/shaped.js, kubejs/server_scripts/expert/recipes/thermal/smelter.js
Nerf Blitz/Blaze/Basalz/Blizz
Reactive armor is gone. Health is reduce. Potion effect remains.
Refactor thermal smelter script because it is apparently an issue on servers and because it's all going to break come next kubejs update anyway...
Increase yields for modular routers items
Servo: 
Turbo Servo: 
Crystal Ball
Energizing Orb
Aluminum moved down to tier 2 crushing so orichalcum can actually be crafted
=> e9e feedback

config/ftbquests/quests/chapters/ars_nouveau_expert.snbt, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/chapter_two.snbt, config/ftbquests/quests/chapters/mekanism_expert.snbt, config/ftbquests/quests/chapters/natures_aura_expert.snbt, config/ftbquests/quests/chapters/occultism_expert.snbt, config/ftbquests/quests/chapters/pneumaticcraft_repressurized_expert.snbt, config/ftbquests/quests/chapters/powah_expert.snbt, kubejs/client_scripts/base/jei_descriptions.js, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/ars_nouveau/book_upgrade.js, kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
- Scribe table returned to early progression. This should allow turrets to be used for some simple automation early on.
- Tier 2 Spellbook changed to maintain gating
- Many quests updated to remove references to disabled items.
=> Potion adjustments

config/ars_nouveau/glyph_aoe.toml, config/configswapper/expert/config/ars_nouveau/glyph_aoe.toml, config/configswapper/expert/config/ars_nouveau/glyph_blink.toml, config/ftbquests/quests/chapters/ars_nouveau.snbt, config/ftbquests/quests/chapters/ars_nouveau_expert.snbt, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/chapter_two.snbt, kubejs/assets/kubejs/lang/en_us.json, kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/server_scripts/base/gamerules/default.js, kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/wild_hunt.js, kubejs/server_scripts/base/recipes/gateways/gateways.js, kubejs/server_scripts/base/tags/blocks/mekanism/cardboard_blacklist.js, kubejs/server_scripts/expert/loot_tables/entities/twilightforest/death_tome.js, kubejs/server_scripts/expert/player_events/starting_items.js, kubejs/server_scripts/expert/recipes/create/compacting.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/immersiveengineering/squeezer.js, kubejs/server_scripts/expert/recipes/occultism/ritual.js, kubejs/server_scripts/expert/recipes/theurgy/shaped.js
- Magic Map Starting Gear fixed
- AoE now tier 1, added to Death Tome loot
- Blood can now be made in a squeezer too. Eyes no longer required.
- Divination Rods reduced to 1 tier, durability increased.
- Wilden Grove gate leash range extended to 256 blocks to avoid them leaping out of the area
- Wilden Grove, Wither Council, and Spawner Rifts now allow mobs to be removed without killing them
- Blink Glyph moved to Tier 2
- Wild Hunt moved to a gateway, more mobs spawned with greater access to skulls
- Default doFireTick to false for new worlds
=> E9E Feedback Changes

config/configswapper/expert/config/quark-common.toml, config/configswapper/normal/config/quark-common.toml
Appleskin does this much better(includes saturation), no reason for quark to add a 2nd food value
=> Disables quark food tooltip

config/jei/recipe-category-sort-order.ini, kubejs/server_scripts/expert/advancements/the_bumblezone.js, kubejs/startup_scripts/base/brewing_registry.js
Resistance potions now take a crate of spinach. 
Fixes advancements for Bumblezone, Queen's Desire.
=> e9e advancements fix and potion tweak

changelogs/CHANGELOG.md, config/configswapper/expert/config/starbunclemania-server.toml, config/configswapper/expert/serverconfig/enigmaticunity-server.toml, config/configswapper/normal/config/starbunclemania-server.toml, config/configswapper/normal/serverconfig/enigmaticunity-server.toml, kubejs/server_scripts/base/recipes/apotheosis/gems/the_nether.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/cnb.js
- Enigmatic Unity Crystals no longer rate limit power transfer. This was preventing them from working nicely with Starbuncles. They still only produce as fast as the old rate limits, however.
- Power storage in the crystals is also buffed. This helps starbies be able to carry more if they have to run a long distance to pick up power. 
- Starbuncle power threshold has been lowered. This allows the starby pick up smaller amounts of power and leave with it. A higher value was leading them to void power in situations where they couldn't pull the threshold value in 1 tick.
- Apotheosis gems are re-balanced following Apotheosis' update as well. 
- Miniboss sporelings now only spawn in twilight forest. Their reactive armor was interacting poorly in the nether if they fell into lava.
=> E9E Power transfer adjustments

config/configswapper/expert/serverconfig/sophisticatedcore-server.toml, config/ftbquests/quests/chapters/storage.snbt, config/ftbquests/quests/chapters/storage_expert.snbt, config/ftbquests/quests/chapters/thermal_series_expert.snbt, config/ftbquests/quests/chapters/villagers.snbt, config/ftbquests/quests/chapters/villagers_expert.snbt, kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/server_scripts/base/loot_tables/chests/minecraft/ancient_city.js, kubejs/server_scripts/base/loot_tables/chests/minecraft/end_city_treasure.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/basement.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/hedge_maze.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_1.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_2.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_3.js, kubejs/server_scripts/base/loot_tables/chests/twilightforest/tree_cache.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js, kubejs/server_scripts/base/recipes/immersiveengineering/shapeless.js, kubejs/server_scripts/expert/loot_tables/chests/enigmatica/delight_loot_boxes.js, kubejs/server_scripts/expert/loot_tables/chests/enigmatica/remove.js, kubejs/server_scripts/expert/loot_tables/chests/immersiveengineering/engineers_house.js, kubejs/server_scripts/expert/loot_tables/chests/pneumaticcraft/mechanic_house.js, kubejs/server_scripts/expert/recipes/nomadictents/shaped.js, kubejs/server_scripts/expert/recipes/pneumaticcraft/pressure_chamber.js, kubejs/server_scripts/expert/recipes/sophisticatedbackpacks/shaped.js, kubejs/server_scripts/expert/recipes/sophisticatedstorage/shaped.js, kubejs/server_scripts/expert/structures/pneumaticcraft/mechanic_house.js
- PNC villager houses now spawn with Arcane Compressors in them. Loot in the chest has been adjusted to remove disabled items
- Erroneously disabled sophisticated storage upgrades have been re-enabled
- Quest fixes
- IE Villager Loot adjusted to remove un-processable materials and give some better loot
- Feeding upgrades should no longer drop from loot
- Nomadic Tent Mallets are now easier to access
- Many loot updates
=> E9E Feedback Adjustments

changelogs/CHANGELOG.md, config/configswapper/expert/config/ars_scalaes/glyph_expand.toml, config/configswapper/expert/config/ars_scalaes/glyph_resize.toml, config/configswapper/expert/config/ars_scalaes/glyph_shrink.toml, config/configswapper/normal/config/ars_scalaes/glyph_expand.toml, config/configswapper/normal/config/ars_scalaes/glyph_resize.toml, config/configswapper/normal/config/ars_scalaes/glyph_shrink.toml, kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/server_scripts/base/recipes/createaddition/rolling.js, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/base/recipes/immersiveengineering/metalpress.js, kubejs/server_scripts/base/recipes/minecraft/smelting.js, kubejs/server_scripts/base/recipes/thermal/press.js, kubejs/server_scripts/base/recipes/thermal/refinery.js, kubejs/server_scripts/expert/loot_tables/chests/enigmatica/ars_nouveau_glyph_cache.js, kubejs/server_scripts/expert/loot_tables/entities/twilightforest/death_tome.js, kubejs/server_scripts/expert/recipes/byg/shaped.js, kubejs/server_scripts/expert/recipes/create/mixing.js, kubejs/server_scripts/expert/recipes/create/shaped.js, kubejs/server_scripts/expert/recipes/create/shapeless.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/online_detector/shaped.js, kubejs/server_scripts/expert/recipes/pneumaticcraft/pressure_chamber.js, kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js, kubejs/server_scripts/expert/recipes/quark/shaped.js, kubejs/server_scripts/expert/recipes/thermal/refinery.js, kubejs/server_scripts/expert/recipes/thermal/smelter.js, kubejs/server_scripts/normal/recipes/thermal/refinery.js
- 1000mb of latex now makes 2 rubber
- TPP may be used to make rubber/cured rubber now. The entire process has changed somewhat as a result.
- Latex comes from the same sources, but TPP can press vines/dandelions for it as well
- Latex is then cooked down to Rubber in the TPP (or other machines)
- The TPP can then cure it with sulfur dioxide. Create still uses fire essence.
- Sulfur Dioxide in turn can be made in the TPP now, making those Fire Essences go much further. 
This entire process in the TPP requires precise temperature controls, similar to biodiesel, so it won't be for everyone. But it offers an alternative to Create at least. 
- Adjustable Chain Drives are now cheaper
- Star Buckets and Starbatteries are now significantly cheaper
- Shrink is now disabled in Expert.
- Ars …
=> Expert improvements

config/configswapper/expert/config/quark-common.toml, config/configswapper/normal/config/quark-common.toml
Moving TEs has been disabled for a while already. Leaving this on with moving TEs disabled, however, appears to cause a crash in some situations.
=> Disable Quark Piston Logic

config/configswapper/expert/config/quark-common.toml
- Re-enable Quark Wraiths in Expert
=> Re-enable Quark Wraiths in Expert

defaultconfigs/darkmodeeverywhere-client.toml
Buuz changed the category names at some point so this config wasn't being applied which makes it sit half behind the EMI buttons.
=> Refresh Dark Mode Everywhere Default Config

changelogs/CHANGELOG.md, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/base/recipes/lychee/dripstone_dripping.js, kubejs/server_scripts/base/recipes/lychee/jei_dummy_recipes.js
Lychee Dummy recipes added to show vanilla mechanics for obtaining Clay and Lava from Dripstone
New recipe added to convert dirt to mud via dripstone
Dripstone > Clay crushing recipe removed due to conflict. Plenty of clay recipes remain.  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/593
=> Dripstone Updates

kubejs/server_scripts/expert/player_events/starting_errors.js, kubejs/server_scripts/expert/player_events/starting_items.js
Due to https://github.com/EnigmaticaModpacks/Enigmatica9/issues/598 some players are starting in the Overworld. 
When this happens, the Twilight Forest is not even registered as a dimension, meaning nothing can be done to 'fix' them on first load. Therefore, we kick them with a message explaining the situation. 
Upon second load, they're teleported safely to the twilight using `TFPortalBlock`. 
Currently, however, once this is complete, the player cannot die... I suspect an issue with the worldspawn location but attempts to fix that via commands have so far failed.
=> Attempting to fix false starts in overworld

changelogs/CHANGELOG.md, config/configswapper/expert/config/quark-common.toml, kubejs/server_scripts/base/loot_tables/blocks/hexerei/mahogany_leaves.js, kubejs/server_scripts/base/loot_tables/blocks/hexerei/willow_leaves.js, kubejs/server_scripts/base/loot_tables/blocks/hexerei/witch_hazel_leaves.js
hide default misleading info about quark ancient tree sapling
increase drop rate of Mahogany saplings to avoid issues early game with not getting enough saplings back from a tree
=> Tree improvements

changelogs/CHANGELOG.md, kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js, kubejs/server_scripts/expert/recipes/occultism/ritual.js
SPS Ports and Supercharged Coils no longer need supreme machine frames as they're included in the Frames themselves.
=> More SPS changes

config/ftbquests/quests/chapters/building.snbt
Allow the construction wand quest to be completed using either a diamond wand, or an infinity wand.
Changed the quest name to be plural to reflect this change.
Changed the icon such that instead of a stone wand (which I think is disabled), it is "air" such that the icon alternates between the diamond wand or infinity wand.
Just a minor but would be appreciated QOL thing. The Infinity Wand recipe is not that hard and can be made in stage 1. It is pretty much better than the diamond one in every way (other than when you accidently click and plop down way too much dirt on the ground), and the recipe does not involve the diamond wand so you cannot even complete the construction wand quest as part of the recipe.
=> Construction wand quest

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/industrial_foregoing_expert.snbt, config/ftbquests/quests/chapters/natures_aura.snbt, config/ftbquests/quests/chapters/natures_aura_expert.snbt, config/ftbquests/quests/chapters/tools_expert.snbt, kubejs/assets/kubejs/lang/en_us.json, kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/cave_troll.js, kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/minoshroom.js, kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/minotaur.js, kubejs/server_scripts/base/recipes/apotheosis/minibosses/twilightforest.js, kubejs/server_scripts/constants/equipment_nbt.js, kubejs/server_scripts/expert/advancements/occultism.js, kubejs/server_scripts/expert/recipes/mekanism/nucleosynthesizing.js
-   [Expert] Infinity Tools are now crafted directly at Artifact tier as they are end game tools.
-  Fixed some bugged quest loot in the Nature's Aura chapter. 
-   Cave Trolls have been buffed with regeneration and knockback effects. 
-   Minotaurs and Minoshrooms can now snare you, making them very dangerous in packs. 
- Death Tome quest now has an associated advancement to assist in triggering it from the ritual.
=> General Improvements

config/inventorysorter-client.toml, defaultconfigs/inventorysorter-client.toml, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/base/recipes/enigmatica/shaped.js
This PR resolves #537 and #587
The issue described in 537 wasn't major, however it was a bit irritating 😅
https://github.com/EnigmaticaModpacks/Enigmatica9/assets/60540476/dae6d7f6-d7bc-45a6-8757-9c03f8ea95ff
The video represents Compacting Drawers now working properly :D It is fast and short because of the github limit, but it does the job done 😅
The only compromise here is lack of tags in the required recipe to make this work, however I think that is worth sacrifice, as in practice no one should get non-EE copper nuggets!
Issue 587 was just a simple config change, that might got forgotten in the pask 2 weeks 😅 I included the fix in this PR instead of doing second one
=> Make Compacting Drawers give Copper Nuggets when Copper Ingot/Block is inserted first + Fix for #587

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/chapter_three.snbt, config/ftbquests/quests/chapters/chapter_two.snbt, kubejs/server_scripts/expert/advancements/the_bumblezone.js
Expert quests leading up to the various teleportation quests now grant the required advancement. These are also granted by simply holding the items for the quest, however, this ensures players in teams don't have to pass the item around just to gain the advancement.
=> Improved quests

changelogs/CHANGELOG.md, kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/data/farmingforblockheads/farmingforblockheads_compat/saplings_for_emeralds.json, kubejs/server_scripts/base/recipes/thermal/tree_extractor.js, kubejs/server_scripts/constants/tree_properties.js, kubejs/server_scripts/constants/wood_properties.js, kubejs/server_scripts/expert/recipes/ars_elemental/shaped.js, kubejs/server_scripts/expert/recipes/ars_nouveau/patchouli_safe_remove.js, kubejs/server_scripts/expert/recipes/ars_nouveau/shaped.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/thermal/shaped.js
Move Spell Sensor and Spell Mirror to early game
Thermal Rubberwood may now be used for latex and can be processed by machines for planks. 
Disabled Thermal energy cart.
=> Expert Recipes for newish items

kubejs/client_scripts/lang_modifications.js
Seems KubeJS fixed the underlying problem that required this code, so it's no longer needed.
=> Update Lang Modification

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/chapter_three.snbt, kubejs/client_scripts/base/jei_descriptions.js, kubejs/server_scripts/base/recipes/create/mixing.js, kubejs/server_scripts/expert/recipes/ars_nouveau/glyph.js, kubejs/server_scripts/expert/recipes/immersiveengineering/fermenter.js, kubejs/server_scripts/expert/recipes/industrialforegoing/laser_drill_ore.js, kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js, kubejs/startup_scripts/base/brewing_registry.js, kubejs/startup_scripts/expert/brewing_remove.js
- XP Melting now requires Superheating in Create to avoid a conflict with potion brewing 
- [Expert] Awkward potions are no longer brewable with Netherwart to promote the use of the far easier to obtain Abjuration Essence
-   [Expert] The Break Glyph no longer requires Iron, making it accessible closer to when a Tier 2 book is available
-   [Expert] Soul powder quest has been updated to help clarify that it can be mined in the Twilight Forest too
=> Brewing fixes

changelogs/CHANGELOG.md, kubejs/client_scripts/lang_modifications.js, kubejs/server_scripts/base/recipes/naturesaura/altar.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/minecraft/stonecutting.js, kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
- Industrial Iron is renamed to Industrial Casing and had it's recipe changed to use sheetmetal https://github.com/EnigmaticaModpacks/Enigmatica9/issues/766
-   Charcoal to Coal conversion with Natures Aura is now significantly faster https://github.com/EnigmaticaModpacks/Enigmatica9/issues/768
-   [Expert] Thermal's mushrooms are now faster to craft in the Ritual of the Forest
=> Casings and Charcoal

changelogs/CHANGELOG.md, kubejs/server_scripts/expert/recipes/immersiveengineering/fermenter.js, kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
energy was set too low, causing the machine to crash. Increased energy consumption but also increased output.
=> fix refinery crash

changelogs/CHANGELOG.md, kubejs/server_scripts/base/tags/mob_effect/ars_nouveau/unstable_gifts.js
Removes potion effects from the Belt of Unstable Gifts that change the way the player sees (FOV or night vision).
Adds a bunch of other fun effects. 
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/801
=> Better Unstable Gifts

config/ftbquests/quests/chapters/tools.snbt, config/ftbquests/quests/chapters/tools_expert.snbt
This PR fixes few of the typos in quests 😄
Words with the `dark background` indicate changes. Crossed out means deletion.
- Tools -> Excavators: Apply Power of the Depth to them to `increase` the depth of mining.
I will keep this PR as draft until I stop playin today, as it's possible I will find few more typos to fix, and doing PR for each change is just making a bit of mess 😄
=> Quest Typo fixes

changelogs/CHANGELOG.md, kubejs/server_scripts/normal/recipes/occultism/crushing.js
Seems we were relying on EE to add back Occultism Crushing recipes for Iron/Gold/Copper and those are no longer handled by it since it's not doing the Raw counterparts for these materials. 
Re-added.
=> More missing crushing recipes

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/thermal_series_expert.snbt, kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/server_scripts/base/recipes/lychee/jei_dummy_recipes.js, kubejs/server_scripts/expert/recipes/thermal/shaped.js
Junk Net is no longer given out as a quest reward as it was buried in the Thermal section.
Instead, the craft is simplified to not require the pressure chamber. 
Additionally, Lychee has been used to add ghost recipes for obtaining straw for the net. 
Quests have been reworked in CH 1 to direct people to the aquatic entangler for ink
Similarly, the Compressed Stone quest has been updated to repeat that Sensitive is not required for crushing the stone
=> Quest clarification surround lead, sensitive, and glyphs in general

changelogs/CHANGELOG.md, kubejs/server_scripts/expert/recipes/mekanism/shaped.js
-   [Expert] Gauge Dropper is no longer gated behind Osmium
=> gauge dropper

kubejs/server_scripts/base/entity_events/hurt/void_safety_net.js, kubejs/server_scripts/expert/recipes/minecraft/shaped.js
This PR Fixes Void Safety Net loop, that was possible to happen on servers due to network latency.
It adds a delay of 40 ticks between teleporation attempts, to allow player from actually teleporting out from the void :D
It also adds a slow falling effect for 4 seconds, to save players from fall damage death after teleporation
Additionally, make the Tripwire hook cheaper, replacing the Iron Ingot with Tin 😄
=> Fix Void Safety Net Latency issues + Fall Damage Death after tp

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/getting_started.snbt, config/ftbquests/quests/chapters/hidden_quests.snbt
-   Hidden quests should no longer show by default when opening the quest book
=> Swap order of Hidden Quest and Getting Started chapters

changelogs/CHANGELOG.md, config/configswapper/expert/config/emendatusenigmatica/material/redstone.json, config/configswapper/normal/config/emendatusenigmatica/material/redstone.json, config/ftbquests/quests/chapters/chapter_one.snbt, config/ftbquests/quests/chapters/tools.snbt, config/ftbquests/quests/chapters/tools_expert.snbt, kubejs/server_scripts/expert/recipes/the_bumblezone/bz_bee_queen_trades.js
- [Expert] Reduce mining level of Redstone to make the early game a little less confusing. Players are seemingly getting stuck thinking they need an Iron Pick to mine it. Certus pick works fine, but this just completely removes any ambiguity. 
-   [Expert] Remove erroneous reference to hoes being used to clear grass 
-   [Expert] Restore missing Dreamstone trade with the Queen Bee
=> Redstone mining level

changelogs/CHANGELOG.md, config/configswapper/expert/config/apotheosis/adventure.cfg, config/configswapper/normal/config/apotheosis/adventure.cfg, kubejs/server_scripts/base/recipes/minecraft/cooking.js, kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
-   [Expert] Adjusted Integral Components recipes to make automating them somewhat easier
The main difference here is that some other recipes use the machine frames on the pedestals, while these used to use them as the central item. This meant dealing with this via filters was clunky. 
-   Add more fun uses for Ars charms 
-   Cicadas, Fireflies, and Backpacks will no longer generate with Apotheosis Affixes. This is mostly to reduce clutter with fireflies and cicadas, but it also removes confusion with backpacks as the affixes only work if worn as an actual chest piece. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/903
=> Integral Components and Charms

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/occultism_expert.snbt, kubejs/server_scripts/expert/recipes/ars_nouveau/glyph.js
-   [Expert] Wind Shear glyph now uses Skyseeker's Blade instead of Iron Swords 
- [Expert] Occultism quests no longer require otherworld ash https://github.com/EnigmaticaModpacks/Enigmatica9/issues/916
=> Fix Wind Shear and Quests

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/hexerei.snbt, config/ftbquests/quests/chapters/hexerei_expert.snbt, kubejs/server_scripts/expert/player_events/armor_sets.js, kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js, kubejs/server_scripts/expert/recipes/ars_nouveau/glyph.js, kubejs/server_scripts/expert/recipes/occultism/ritual.js
-   [Expert] Skyseeker's Boots no longer provide step up. Even setting it to a lower height was too much and there's no good way to disable it.  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/919
- Hexerei drying rack quests now accept any drying rack https://github.com/EnigmaticaModpacks/Enigmatica9/issues/918
-   [Expert] Ars Nouveau threads that require a familiar shard now also accept the corresponding charm 
-   [Expert] Fix broken Parrot Familiar summon
=> Small fixes

changelogs/CHANGELOG.md, config/ftbquests/quests/chapters/ars_nouveau.snbt, config/ftbquests/quests/chapters/ars_nouveau_expert.snbt, kubejs/server_scripts/expert/recipes/mekanism/shaped.js
- Tablet of Awakening quest no longer requires an Amethyst Golem Charm https://github.com/EnigmaticaModpacks/Enigmatica9/issues/924
-  [Expert] Mekanism Teleporter Frames now craft in batches of 9  https://github.com/EnigmaticaModpacks/Enigmatica9/issues/925
=> Golems and Teleporters

kubejs/client_scripts/constants/jei_hidden_disabled.js, kubejs/client_scripts/expert/textures.js, kubejs/server_scripts/expert/recipes/enigmatica/remove.js, kubejs/server_scripts/expert/recipes/thermal/smelter.js
I feel like it deserves to stay given its functionality is beyond acting like Engineer's Goggles. I changed the Expert Mode texture to use default PNC upgrade as a base and added a recipe that uses it as well, so no extra items are used.
=> Reintroduce Mechanical Visor Upgrade to Expert mode

changelogs/CHANGELOG.md, kubejs/server_scripts/base/recipes/ars_nouveau/shaped.js, kubejs/server_scripts/base/recipes/ars_scalaes/shaped.js, kubejs/server_scripts/base/recipes/enigmatica/remove.js, kubejs/server_scripts/base/recipes/immersiveengineering/shaped.js, kubejs/server_scripts/base/recipes/minecraft/stonecutting.js, kubejs/server_scripts/base/tags/blocks/forge/workbenches.js, kubejs/server_scripts/base/tags/items/forge/workbenches.js, kubejs/server_scripts/expert/recipes/ae2/shapeless.js, kubejs/server_scripts/expert/recipes/thermal/smelter.js
-   Crafting tables may now be converted to variants with the stonecutter. Variant shaped crafting recipes are removed. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/965
- Immersive Engineering Sawdust flooring changed to no longer conflict with thermal
- Add Expert recipe for PNC's new drone chunkloader
=> Recipe conflicts

changelogs/CHANGELOG.md, kubejs/data/farmingforblockheads/farmingforblockheads_compat/mushrooms_for_emeralds.json, kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_emerald.json, kubejs/server_scripts/base/loot_tables/entities/cnb/sporeling.js, kubejs/server_scripts/base/recipes/byg/shaped.js
-   Removed duplicate Cabbage seeds in the Market 
-   Add many shrooms to the Market https://github.com/EnigmaticaModpacks/Enigmatica9/issues/974
-   Add methods of obtaining various BYG soils for planting
-   Sporelings in the End may now drop end shrooms
=> Market Improvements

kubejs/server_scripts/expert/recipes/create/sequenced_assembly.js, kubejs/server_scripts/expert/recipes/create/shaped.js
This PR makes Create Train Tracks much cheaper to craft and Train Controls available in chapter 1.
Create Trains are amazing and most of us love them, but they are objectively worse automation option when compared to "industry titans" like AE2, and so to make players consider them as a practical option, trains must be very cheap, and, unfortunately, this is currently not the case in E9E:
- Train tracks are pretty expensive. Laying down a track to a nearby dungeon can easily take all the copper you mined from the nearby hollow hill or two
- Train Controls are gated midway into chapter 2. Due to lumium gear requirement, you can only start using trains at the point in the progression where you are also already have access to AE2 quantum ring, at which point trains are just a novelty choice …
=> Train recipes rebalance
